### ISSUE TITLE
Too Simple! 🏄 

### ISSUE THREAD

**Issue by kumarharsh** [LeaVerou/duoload#1]
Just wow - there's barely any code! Kudos 👏 

Although it doesn't seem to be loading load some sites. Maybe my network is bad...

**Comment by kumarharsh** [comment]
No, it seems like it's due to the `X-Frame-Options` header set to `SAMEORIGIN`. Nevermind...

**Comment by EmilStenstrom** [comment]
Same issue here. If the external website has X-Frame-Options set, none of the two websites seem to be loading.
